"""add_auth_admin_fields

Revision ID: ee4982e80818
Revises: ab2999f537a1
Create Date: 2026-03-08 18:49:42.561401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4982e80818'
down_revision: Union[str, Sequence[str], None] = 'ab2999f537a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('admin_status', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('user_login_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_login_id'), 'users', ['user_login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_login_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'user_login_id')
    op.drop_column('reports', 'is_approved')
    op.drop_column('reports', 'admin_status')
    # ### end Alembic commands ###
